server:
  port: 9999

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ~
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2db

#foo: value_of_foo
#boo_as_list: [1,2,3,4]
#boo_as_list_2:
#  - 1
#  - 2
#  - 3
#dictionary:
#  foo:
#    boo:
#      zoo: x
#  alfa: omega
